"""The explicit /agent entry point over the allowlisted read-only tool loop."""

from __future__ import annotations

import logging
from typing import Protocol

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langgraph.errors import GraphRecursionError

from steward.answer.gateway import ModelGatewayError
from steward.events import IncomingEvent
from steward.presentation import PresentedReply


_LOGGER = logging.getLogger(__name__)


class ToolAgentGraph(Protocol):
    """Minimal safe surface for the pre-built restricted tool graph."""

    def invoke(self, input: dict[str, object], config: dict[str, object]) -> dict[str, object]: ...


class StewardToolAgentApplication:
    """Expose the allowlisted read-only tool loop through the explicit /agent command."""

    def __init__(self, graph: ToolAgentGraph) -> None:
        self._graph = graph

    def handle_command(self, event: IncomingEvent) -> str | PresentedReply | None:
        command, separator, question = (event.text or "").strip().partition(" ")
        command = command.partition("@")[0]
        if command != "/agent":
            return None
        if not separator or not question.strip():
            return "Use /agent followed by a question that may need Steward's read-only tools."
        return self._ask(question.strip(), event)

    def _ask(self, question: str, event: IncomingEvent) -> str | PresentedReply:
        reply_text = (event.reply_text or "").strip()
        if reply_text:
            context = reply_text[:2_000]
            suffix = "…" if len(reply_text) > len(context) else ""
            question = f"Reply context (user-supplied): {context}{suffix}\n\nCurrent question: {question}"
        try:
            result = self._graph.invoke(
                {
                    "messages": [
                        SystemMessage(
                            "You are Steward. Use only supplied allowlisted read-only tools when needed. "
                            "Never claim a tool result you did not receive; answer as soon as the result is sufficient."
                        ),
                        HumanMessage(question),
                    ]
                },
                {"configurable": {"thread_id": f"tool-agent:{event.platform}:{event.chat_id}"}, "recursion_limit": 16},
            )
        except GraphRecursionError:
            return (
                "I stopped the tool workflow before it could loop further. "
                "No write was performed; please narrow the request and try again."
            )
        except ModelGatewayError:
            return "The configured model is temporarily unavailable. Please retry later or use a local model."
        except Exception as error:
            # The tool graph joins provider adapters, SQLite-backed read tools,
            # and LangGraph.  An unexpected adapter failure must not crash the
            # Telegram update handler or expose diagnostics such as paths,
            # tokens, or provider payloads.  The graph has no write tools.
            _LOGGER.warning("Read-only tool workflow failed (%s).", type(error).__name__)
            return (
                "The read-only tool workflow is temporarily unavailable. "
                "No change was made; please retry later or use a narrower question."
            )
        messages = result.get("messages")
        if not isinstance(messages, list) or not messages:
            return "The tool agent returned no final response."
        final = messages[-1]
        content = str(final.content)
        # Test doubles and third-party graph adapters may return a minimal
        # message-like object. Preserve that transport-neutral contract while
        # production LangChain messages get an explicit provenance card.
        if not isinstance(final, AIMessage):
            return content
        last_request = max(
            (index for index, message in enumerate(messages) if isinstance(message, HumanMessage)),
            default=len(messages),
        )
        tool_names = {
            message.name for message in messages[last_request + 1:]
            if isinstance(message, ToolMessage) and message.name
        }
        if not tool_names:
            return PresentedReply(
                content + "\n\nOrigin: generated by the configured model; Steward did not search your saved material for this reply.",
                title="Generated answer", icon="💬",
            )
        local_tools = {"search_sources", "read_source", "search_activity"}
        if tool_names <= local_tools:
            title, origin = "Answer using saved material", "Origin: Steward searched your local saved material."
        else:
            title, origin = "Answer using Steward tools", "Origin: Steward used the listed read-only local tools."
        return PresentedReply(f"{content}\n\n{origin}", title=title, icon="🔎")
